### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oltolm** [matwachich/iup#5]
What is the license of this project? It's impossible to use this library without one.

**Comment by matwachich** [comment]
Public domain
Credits appreciated :)

**Comment by oltolm** [comment]
Thanks for the reply. Please add a file named LICENSE to the repository and choose [Unlicense](https://choosealicense.com/licenses/#unlicense) as the license. This puts the library into public domain. See [this link](https://help.github.com/articles/licensing-a-repository/#applying-a-license-to-a-repository-with-an-existing-license) for more information.
